export const siteConfig = {
  name: 'Priyanshu Chawda',
  shortName: 'Priyanshu',
  url: 'https://priyanshuworks.tech',
  locale: 'en_US',
  language: 'en-US',
  title: 'Priyanshu Chawda | AI Engineer - Agentic Systems & Developer Tools',
  description:
    'Priyanshu Chawda is an AI Engineer building agentic systems, LLM orchestration, MCP servers, developer tools, and scalable full-stack software.',
  shortDescription: 'AI Engineer building agentic systems and developer tools.',
  email: 'priyanshuchawda20@gmail.com',
  twitterHandle: '@priyanshuchawda',
  github: 'https://github.com/priyanshuchawda',
  linkedin: 'https://www.linkedin.com/in/priyanshuchawda',
  keywords: [
    'Priyanshu Chawda',
    'AI Engineer',
    'Agentic Systems',
    'LLM Orchestration',
    'MCP Servers',
    'Developer Tools',
    'Machine Learning',
    'Software Engineer',
    'Full Stack Developer',
    'Next.js Developer',
    'TypeScript',
    'Python',
    'Portfolio',
  ],
  knowsAbout: [
    'Artificial Intelligence',
    'Machine Learning',
    'Large Language Models',
    'Agentic Systems',
    'MCP Servers',
    'LLM Orchestration',
    'Full Stack Development',
    'Next.js',
    'TypeScript',
    'Python',
  ],
} as const;

export const sameAsLinks = [siteConfig.github, siteConfig.linkedin] as const;
