export const siteConfig = {
  name: 'Priyanshu Chawda',
  shortName: 'Priyanshu',
  url: 'https://priyanshuworks.tech',
  locale: 'en_US',
  language: 'en-US',
  title: 'Priyanshu Chawda | AI Software Engineer',
  description:
    'Priyanshu Chawda is an AI-focused software engineer building agentic systems, MCP servers, developer tools, and AI apps.',
  shortDescription:
    'AI-focused software engineer building agentic systems and developer tools.',
  jobTitle: 'AI-focused Software Engineer',
  email: 'priyanshuchawda20@gmail.com',
  twitterHandle: '@priyanshuchawda',
  twitter: 'https://x.com/priyanshuchawda',
  github: 'https://github.com/priyanshuchawda',
  linkedin: 'https://www.linkedin.com/in/priyanshuchawda',
  lastUpdated: '2026-04-29',
  keywords: [
    'Priyanshu Chawda',
    'AI-focused software engineer',
    'AI Engineer',
    'Agentic Systems',
    'MCP server developer',
    'MCP Servers',
    'Developer tools',
    'Generative AI engineer',
    'RAG systems',
    'Gemini AI',
    'LLM Orchestration',
    'LLM workflows',
    'Automation systems',
    'Machine Learning',
    'Software Engineer',
    'Full-stack developer',
    'Next.js',
    'TypeScript',
    'Python',
    'Pune, India',
    'AI engineer Pune',
    'B.Tech Computer Science',
    'AI engineering services',
    'Portfolio',
  ],
  knowsAbout: [
    'Artificial Intelligence',
    'Machine Learning',
    'Large Language Models',
    'Agentic Systems',
    'MCP Servers',
    'LLM Orchestration',
    'LLM Workflows',
    'Gemini AI',
    'Automation Systems',
    'Full Stack Development',
    'Next.js',
    'TypeScript',
    'Python',
  ],
} as const;

export const sameAsLinks = [
  siteConfig.github,
  siteConfig.linkedin,
  siteConfig.twitter,
] as const;
